In [1]:
n = int(input("Input the number of rows "))
for i in range(n):
    for j in range(n):
        print("*", end = " ")
    print()    

Input the number of rows5
* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [3]:
n = int(input("Input the number of rows "))
for i in range(n):
    for j in range(1+i):
        print("*", end = " ")
    print()    

Input the number of rows 5
* 
* * 
* * * 
* * * * 
* * * * * 


In [9]:
n = int(input("Input the number of rows "))
for i in range(n):
    for j in range(i+1):
        print("*", end = " ")
    print()

Input the number of rows 5
* 
* * 
* * * 
* * * * 
* * * * * 


In [8]:
n = int(input("Input the number of rows "))
for i in range(n):
    for j in range(i, n):
        print(" ", end = " ")
    for j in range(i+1):
        print("*", end = " ")
    print()

Input the number of rows 5
          * 
        * * 
      * * * 
    * * * * 
  * * * * * 


In [10]:
n = int(input("Input the number of rows "))
for i in range(n):
    for j in range(i+1):
        print(" ", end = " ")
    for j in range(i, n):
        print("*", end =" ")
    print()    

Input the number of rows 5
  * * * * * 
    * * * * 
      * * * 
        * * 
          * 


In [13]:
import numpy as np
a = np.array([
    [3, 7],
    [-4, -6],
    [7, 8],
    [1, -1],
    [-4, -1],
    [-3, -7],
])


In [14]:
a

array([[ 3,  7],
       [-4, -6],
       [ 7,  8],
       [ 1, -1],
       [-4, -1],
       [-3, -7]])

In [16]:
import pandas as pd

In [18]:
df = pd.DataFrame(a, columns = ['a0', 'a1'])

In [19]:
df

a0  a1
0   3   7
1  -4  -6
2   7   8
3   1  -1
4  -4  -1
5  -3  -7

In [20]:
a0 = a[:,0]
a1 = a[:,1]

In [21]:
a0

array([ 3, -4,  7,  1, -4, -3])

In [22]:
a1

array([ 7, -6,  8, -1, -1, -7])

In [23]:
np.cov(a0,a1)

array([[20., 25.],
       [25., 40.]])

In [24]:
a

array([[ 3,  7],
       [-4, -6],
       [ 7,  8],
       [ 1, -1],
       [-4, -1],
       [-3, -7]])

In [25]:
a.T

array([[ 3, -4,  7,  1, -4, -3],
       [ 7, -6,  8, -1, -1, -7]])

In [28]:
sigma = a.T @a/5

In [29]:
sigma

array([[20., 25.],
       [25., 40.]])

In [30]:
np.linalg.eig(sigma)

(array([ 3.07417596, 56.92582404]), array([[-0.82806723, -0.56062881],
        [ 0.56062881, -0.82806723]]))